version: "3.5"
services:
  app:
    container_name: bacen-pix-mock
    build:
      context: ../
      dockerfile: ./development/Dockerfile
    ports:
      - 80:80
    volumes:
      - ../:/home/app
    links:
      - mongo
    networks:
      - app_network

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_BASICAUTH_USERNAME: ${MONGO_EXPRESS_USER}
      ME_CONFIG_BASICAUTH_PASSWORD: ${MONGO_EXPRESS_PASSWORD}
      ME_CONFIG_MONGODB_URL: ${MONGO_CONNECTION_URL}
    links:
      - mongo
    networks:
      - app_network
    depends_on:
      - mongo
    restart: always

  mongo:
    image: mongo
    container_name: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    ports:
      - ${MONGO_PORT}:${MONGO_PORT}
    volumes:
      - ./cache:/data/db
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
